version: "2"
services:
  rucio:
    image: rucio/rucio-server:release-1.21.6
    hostname: act-ldmx.cern-test.uiocloud.no
    ports:
      - "443:443"
    volumes:
      - /etc/grid-security/certificates:/etc/grid-security/certificates
      - /etc/grid-security/hostcert.pem:/etc/grid-security/hostcert.pem
      - /etc/grid-security/hostkey.pem:/etc/grid-security/hostkey.pem
      - /opt/rucio/etc:/opt/rucio/etc
    environment:
      - RUCIO_ENABLE_SSL=True
      - RUCIO_HOSTNAME=act-ldmx.cern-test.uiocloud.no
      - RUCIO_CFG_DATABASE_DEFAULT=postgresql://rucio:secret@ruciodb/rucio
      - RUCIO_CA_PATH=/etc/grid-security/certificates
      - RUCIO_ENABLE_LOGFILE=True
